[tool.poetry]
name = "webdav"
version = "0.1.0"
description = ""
authors = ["Veronika Gillies <veronikamwinters@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pywebdav3 = "^0.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
